GET http://localhost:5000/api/user/aaaaaa

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name" : "Tạ Quang Hữu",
    "email": "user8@gmail.com", 
    "password": "123456",
    "phone": "0377033450"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "user4@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ1c2VyNEBnbWFpbC5jb20iLCJyb2xlX2NvZGUiOiJSMiIsImlhdCI6MTc0NTI2MDEwMCwiZXhwIjoxNzQ1NjkyMTAwfQ.j90BrlnjD2l6i2Up3S__Rk-l5AADCesKdloyzBDbw8I

# {
#     "email": "user4@gmail.com",
#     "password": "123456"
# }

###
POST http://localhost:5000/api/location/
Content-Type: application/json

{
    "text": ""
}

###
POST http://localhost:5000/api/schedule/
Content-Type: application/json

{
    "fromLocationId": "1",
    "toLocationId": "19",
    "date": "2025-04-22"
}

###
POST http://localhost:5000/api/booking/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ1c2VyNEBnbWFpbC5jb20iLCJyb2xlX2NvZGUiOiJSMiIsImlhdCI6MTc0NTI2MDEwMCwiZXhwIjoxNzQ1NjkyMTAwfQ.j90BrlnjD2l6i2Up3S__Rk-l5AADCesKdloyzBDbw8I

{
    "scheduleId": "19",
    "seat": ["A01", "A02"]
}