GET http://localhost:5000/api/user/aaaaaa

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name" : "Nguyễn Công Tuấn Đẹp Trai",
    "email": "user1@gmail.com", 
    "password": "123456",
    "phone": "0377033450"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGVfY29kZSI6IlIyIiwiaWF0IjoxNzQ2MTU2ODcxLCJleHAiOjE3NDY1ODg4NzF9.snNUGuRmaHU6l17SGW8HO_CZHbAwOGdGz2T0NuH4x3Y

# {
#     "email": "user4@gmail.com",
#     "password": "123456"
# }

###
POST http://localhost:5000/api/location/
Content-Type: application/json

{
    "text": ""
}

###
POST http://localhost:5000/api/schedule/
Content-Type: application/json

{
    "fromLocationId": "1",
    "toLocationId": "19",
    "date": "2025-04-15"
}

###
POST http://localhost:5000/api/schedule/
Content-Type: application/json

{
    "fromLocationId": "1",
    "toLocationId": "19",
    "date": "2025-04-15"
}

###
POST http://localhost:5000/api/schedule/detail
Content-Type: application/json

{
    "id": "20"
}

###
POST http://localhost:5000/api/booking/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGVfY29kZSI6IlIyIiwiaWF0IjoxNzQ2MTU2ODcxLCJleHAiOjE3NDY1ODg4NzF9.snNUGuRmaHU6l17SGW8HO_CZHbAwOGdGz2T0NuH4x3Y

{
    "scheduleId": "20",
    "seats": ["137", "140"]
}

###
POST http://localhost:5000/api/booking/detail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGVfY29kZSI6IlIyIiwiaWF0IjoxNzQ2MTU2ODcxLCJleHAiOjE3NDY1ODg4NzF9.snNUGuRmaHU6l17SGW8HO_CZHbAwOGdGz2T0NuH4x3Y

{
    "id": "1"
}

###
POST http://localhost:5000/api/seat/
Content-Type: application/json

{
    "scheduleId": "5"
}