GET http://localhost:5000/api/user/aaaaaa

###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name" : "Nguyễn Công Tuấn Đẹp Trai",
    "email": "user1@gmail.com", 
    "password": "123456",
    "phone": "0377033450"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "user@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/api/auth/change_password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGVfY29kZSI6IlIyIiwiaWF0IjoxNzQ2MTU2ODcxLCJleHAiOjE3NDY1ODg4NzF9.snNUGuRmaHU6l17SGW8HO_CZHbAwOGdGz2T0NuH4x3Y

{
    "oldPassword": "1234567",
    "password": "123456"
}

###
GET http://localhost:5000/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGVfY29kZSI6IlIyIiwiaWF0IjoxNzQ2MTU2ODcxLCJleHAiOjE3NDY1ODg4NzF9.snNUGuRmaHU6l17SGW8HO_CZHbAwOGdGz2T0NuH4x3Y

# {
#     "email": "user4@gmail.com",
#     "password": "123456"
# }

###
POST http://localhost:5000/api/location/
Content-Type: application/json

{
    "text": ""
}

###
POST http://localhost:5000/api/schedule/
Content-Type: application/json

{
    "fromLocationId": "1",
    "toLocationId": "19",
    "date": "2025-04-15"
}

### api lấy danh sách chuyến đi từ location 1 đến location 19 vào ngày 2025-04-15
POST http://localhost:5000/api/schedule/
Content-Type: application/json

{
    "fromLocationId": "1",
    "toLocationId": "19",
    "date": "2025-04-15"
}

###lấy chi tiết danh sách chuyến đi -> call ở booking
POST http://localhost:5000/api/schedule/detail
Content-Type: application/json

{
    "id": "1"
}

###
POST http://localhost:5000/api/booking/
Content-Type: application/json

{
    "name": "Nguyễn Công Tuấn Đẹp Trai",
    "email": "tuang146@gmail.com",
    "phone": "0377033450",
    "scheduleId": "1",
    "seats": ["5", "6"]
}

###lấy thông tin chi tiết booking by id -> call ở payment -> call api user -> call api schedule by id
POST http://localhost:5000/api/booking/detail
Content-Type: application/json

{
    "id": "3"
}

###
POST http://localhost:5000/api/booking/get_all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGVfY29kZSI6IlIyIiwiaWF0IjoxNzQ5MTU3ODU1LCJleHAiOjE3NDk1ODk4NTV9.p0XH7dAGZ_a_AGOMepmRnzyRuMXQkxNzScLJuwCTL1w

{
    
}

###lấy tình trạng từng ghế trong chuyến đi -> call ở booking 0: không, 1: có
POST http://localhost:5000/api/seat/
Content-Type: application/json

{
    "scheduleId": "1"
}

###call khi customer nhấn xác nhận thanh toán -> call ở payment
POST http://localhost:5000/api/payment/
Content-Type: application/json

{
    "bookingId": "3"
}


###tất cả những api dưới đều phải đăng nhập admin sau đó truyền access token vào header

###Get all route
POST http://localhost:5000/api/route/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGVfY29kZSI6IlIxIiwiaWF0IjoxNzQ5NTY3MjUxLCJleHAiOjE3NDk5OTkyNTF9.xosS4P7ZpqErLTcyceKEen3hHTIrRKXl0e89XXe0Eks

{
    
}

###Truyền routeId vào để lấy list schedule của route đó
POST http://localhost:5000/api/schedule/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGVfY29kZSI6IlIxIiwiaWF0IjoxNzQ5NTY3MjUxLCJleHAiOjE3NDk5OTkyNTF9.xosS4P7ZpqErLTcyceKEen3hHTIrRKXl0e89XXe0Eks

{
    "routeId": "1"
}

###Add thêm schedule
POST http://localhost:5000/api/schedule/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGVfY29kZSI6IlIxIiwiaWF0IjoxNzQ5NTY3MjUxLCJleHAiOjE3NDk5OTkyNTF9.xosS4P7ZpqErLTcyceKEen3hHTIrRKXl0e89XXe0Eks

{
    "routeId": "1",
    "departureTime": "06:00:00",
    "arrivalTime": "20:00:00",
    "Date": "2025-04-15",
    "price": 500000,
    "busType": "BUS2T"
}

###Update schedule (phải truyền scheduleId, còn lại có thể truyền hoặc không)
POST http://localhost:5000/api/schedule/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGVfY29kZSI6IlIxIiwiaWF0IjoxNzQ5NTY3MjUxLCJleHAiOjE3NDk5OTkyNTF9.xosS4P7ZpqErLTcyceKEen3hHTIrRKXl0e89XXe0Eks

{
    "scheduleId": "2",
//    "departureTime": "06:00:00",
  //  "arrivalTime": "20:00:00",
    //"Date": "2025-04-15",
    "price": 700000,
    "busType": "BUS2T"
}

###Delete schedule bằng scheduleId
POST http://localhost:5000/api/schedule/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQGdtYWlsLmNvbSIsInJvbGVfY29kZSI6IlIxIiwiaWF0IjoxNzQ5NTY3MjUxLCJleHAiOjE3NDk5OTkyNTF9.xosS4P7ZpqErLTcyceKEen3hHTIrRKXl0e89XXe0Eks

{
    "scheduleId": "1"
}